### ISSUE TITLE
GPU generated batch contains several wrong frames

### ISSUE THREAD

**Issue by voeykovroman** [dmlc/decord#31]
First of all, thank you for this amazing work, it seems like it will save a lot of time usually spent on generating datasets from video.
However, I have encountered a strange bug when using gpu-accelerated batch generation.
First batch contains every frame I asked for but when I try to get another batch with different frame indexes it contains one (or more) first frame near the final index of the previous batch and only after that there are correct frames until the new final index.

Below I attach code example to reproduce this behavior in Jupyter Notebooks

```
from decord.bridge.torchdl import to_torch
from decord import VideoReader
from decord import gpu, cpu
import matplotlib.pyplot as plt


vr = VideoReader('path_to_video.mp4', ctx=gpu(0))

first_sample = vr.get_batch([range(2500, 2510, 1)])
first_sample = to_torch(first_sample)

second_sample = vr.get_batch([range(3500, 3510, 1)])
second_sample = to_torch(second_sample)

fig = plt.figure(figsize=(25, 25))
for i in range(first_sample.shape[0]):
    img1 = first_sample[i].cpu().numpy()
    ax = plt.subplot(first_sample.shape[0], 2, i*2+1)
    ax.axis('off')
    plt.imshow(img1)
    plt.title('first_sample')
    
    img2 = second_sample[i].cpu().numpy()
    ax = plt.subplot(first_sample.shape[0], 2, i*2+2)
    ax.axis('off')
    plt.imshow(img2)
    plt.title('second_sample')
plt.show()
```

**Comment by zhreshold** [comment]
I'll take a look, btw, do you notice the same issue using cpu?

**Comment by voeykovroman** [comment]
No, I’ve checked with cpu and every batch was correct.

**Comment by zhreshold** [comment]
#38 should fix the problem by now. I will investigate the root cause better later.

**Comment by voeykovroman** [comment]
Thanks a lot! I’ll check it out in couple hours and write about results here

**Comment by voeykovroman** [comment]
I rebuilt from master just now but problem is actually still persisting. Maybe it's my local environment incompatibilities. 
If it matters it is:
Nvidia GTX 1080 Ti
Driver version 430.64
CUDA 10.1
Ffmpeg 4.2
All of these inside Docker container (deployed with NVIDIA Container Toolkit)

**Comment by zhreshold** [comment]
@voeykovroman can you show me the visuals and if possible can you also provide the source video file so I can try to reproduce it

**Comment by voeykovroman** [comment]
```


from decord.bridge.torchdl import to_torch
from decord import VideoReader
from decord import gpu, cpu
import matplotlib.pyplot as plt


vr = VideoReader('/workdir/data/raw_data/test.mp4', ctx=gpu(0))

first_sample = vr.get_batch([range(500, 510, 1)])
first_sample = to_torch(first_sample)

second_sample = vr.get_batch([range(750, 760, 1)])
second_sample = to_torch(second_sample)

fig = plt.figure(figsize=(25, 25))
for i in range(first_sample.shape[0]):
    img1 = first_sample[i].cpu().numpy()
    ax = plt.subplot(first_sample.shape[0], 2, i*2+1)
    ax.axis('off')
    plt.imshow(img1)
    plt.title('first_sample')
    
    img2 = second_sample[i].cpu().numpy()
    ax = plt.subplot(first_sample.shape[0], 2, i*2+2)
    ax.axis('off')
    plt.imshow(img2)
    plt.title('second_sample')
plt.show()
```

![decord_test](https://user-images.githubusercontent.com/32206490/77094006-e3b2dd00-6a1c-11ea-8ee8-3a86df8af799.png)
Video may be downloaded [here](https://gofile.io/?c=wCIsb4)
This is 120 fps video recorded with Basler camera with h264_nvenc codec and maybe that's the problem, because with your last fix the bug has gone for usual files (like standard youtube 30 fps videos), but it persists for such high frame rate videos.

**Comment by zhreshold** [comment]
Merged fix #43, I checked the problem is solved. It was due to the uncleared buffer in CUVID decoding parser during frame seeking.
